[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "magtrack"
description = "Convert images of beads into XYZ positions"
version = "0.5.0"
readme = "README.md"
authors = [
    {name = "James London", email = "7jameslondon@gmail.com" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
license = "GPL-3.0"
license-files = ["license"]
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
cpu = []
gpu = ["cupy-cuda12x>=13.0; sys_platform != 'darwin'"]

[project.urls]
Homepage = "https://github.com/7jameslondon/MagTrack"
Issues = "https://github.com/7jameslondon/MagTrack/issues"

[tool.setuptools]
packages = ["magtrack"]